### ISSUE TITLE
to remove && ~isempty(uniformUdot)

### ISSUE THREAD

**Issue by TheChikenfly** [ONSAS/ONSAS.m#511]
Mauricio can you remove the && ~isempty(uniformUdot) line &-é of HydroframeForce plz?

**Comment by mvanzulli** [comment]
@TheChikenfly  The problem here is that `uniformUdot`global variable only has effect on VIV problems. Hence you need to define  it alongside the other VIV global variables always. I think we can keep the global at this stage and then if in the future is not useful we can remove it, but might be helpful for some validation examples. What do you think?

**Comment by TheChikenfly** [comment]
OK I agree let's do this

**Comment by jorgepz** [comment]
Hi. I agree that we can re.structure all the viv variables when we include the wom function in ONSAS. By now if everything works i would leave it. Did u have any problem @TheChikenfly ? I close the issue by the moment and please reopen it if u have errors to fix or some change that u need to make something work. Thanks
